### ISSUE TITLE
how to get `wat` output from a decompiled `wasm` file

### ISSUE THREAD

**Issue by hoebat** [helins/wasm.cljc#2]
Is there a way to convert to and from `wat` format instead of having raw bytes?

It's a bit more readable when decompiled.

**Comment by helins** [comment]
So, I was kind of excited by `wat` at first. That was my initial plan, work with `wat` files read as Clojure data structures. The problem is that it is ambiguous: https://github.com/WebAssembly/design/issues/1400

There is no "canonical" format,  so parsing `wat` is more complex than it should. In the end, I also found it wasn't that useful beyond simple examples. I found that Clojure data structures mirroring the binary format is more useful, way easier to work with.

Nonetheless, would you have a use case? :)

**Comment by hoebat** [comment]
@helins, when you're talking about it being 'ambiguous' you mean that the parens are optional right?

That's not a huge issue for me. I'd just go with leaving the parens in there.

- I see what the others on the thread are saying. Most people don't like parens. The people that do tend to like seeing the structure in the code upfront whereas the people that don't just want to be expressive.

 - You don't necessarily have to influence the wat spec to be able to produce a file that conforms to what you suggested with tightening the wat spec -> as long as the wat interpreter understands the input, it doesn't matter whether there's parens or not.

**Comment by helins** [comment]
Not only parens from what I remember. I was working on this a little while ago so I don't remember exact examples but quite often there was more than one way to write something, which is not the case in the binary format. So parsing WAT was looking like too much work for something that wouldn't add much value. Indeed, if all you have is a WAT file, there are tools for converting it to the bin format and then you are good to go for this lib.

Outputting WAT on the other hand wouldn't be too hard by transforming the Clojure data structures mimicking the structure of bin format. However, you could once again just output a bin file and use a CLI tool to turn it into a WAT file.

My original idea was to parse the bin format into Clojure data structures that mimicks WAT. Besides the above, it really wasn't a good idea because it was clunky to operate over it, transform in any way ; you have to work with list, that sometimes may or may not contain some arguments... It's way better to have unambiguous maps and vectors IMO.

**Comment by hoebat** [comment]
I looked at `wasm.clj` and thought you had a version of the decomplier in there in the earlier versions but I couldn't find it in the latest one.

No real use case at the moment but I was looking at being able to inject wasm code into a container. I have a pseudo language (xtalk) that can currently transpile to dynamic languages right now (ie. js and python) ie.

```
(defn.xt arr-foldl
  [arr f init]
  (var out := init)
  (k/for:array [e arr]
    (:= out (f out e)))
  (return out))
```

would transpile to:

```
function arr_foldl(arr,f,init){
  let out = init;
  for(let e of arr){
    out = f(out,e);
  };
  return out;
}
```

 I'd love to be able to generate wasm but I feel like it's going to be a bit of a time sink for me as it's more on the assembly level and it's typed.

But yeah, it'd be really interesting to write some immutable datastructures in wat/talk.

**Comment by hoebat** [comment]
hang on... how are maps and vectors represented in wat?

here's fold for three more languages. it's an easy transpile if the datastructures are there. the transpiler supports types as well (c) but it'd be great if there were some sort of standard types in wat.

```lua
local function arr_foldl(arr,f,init)
  local out = init
  for _, e in  ipairs(arr) do
    out = f(out,e)
  end
  return out
end
```

```python
def arr_foldl(arr,f,init):
  out = init
  for e in arr:
    out = f(out,e)
  return out
```

```R
arr_foldl <- function (arr,f,init){
  out <- init;
  for(e in arr){
    out <- f(out,e);
  };
  return(out);
};
```

**Comment by helins** [comment]
Decompiler, regarding WAT you mean? From what I remember, WAT was not too far from being almost EDN compatible when it comes to reading it. Maybe one thing or two to watch out but using `clojure.tools.reader.edn` often worked.

If all you care about is outputting WAT, then you don't even need my library frankly. You can produce Clojure data and then print it. One hack is that when where is something that you can represent directly, you can use `symbol`. E.g. if you want to output a number as hex, you can `(symbol "0x42")` and when it prints, it will be fine.

**Comment by helins** [comment]
There are no maps or vectors in WAT, it's really minimalistic. There are efforts towards having things like structures, kind of, but I'm not sure what's the status currently. It's best to read about WASM as such, keeping in mind that WAT is merely a text format so that it becomes a bit more human readable.

**Comment by hoebat** [comment]
wow... it's really low level. I don't think I can afford to spend much time on this right now - as tempting as it is.

I did mention it on the convex discord that you guys should look into targeting wasm though I did skim through the convex implementation and the convex lisp language is probably a bit too high level to target wasm and given that's it's immutable, it'll be hard to do.

------

Would you know how similar wasm is to jvm byte code? Like in terms of the primitives. I thought that wasm looked a bit more high level than byte code but I didn't realise it was so low level.

------

I've mainly been working on xtalk (crosstalk) at the moment. 

One advantage of using `xtalk` is that I can write in lisp and have it target various platforms using the same shared code. It's kind of like cljs/clj for front/back but the targets are arbitrary ie - js/lua. It aims to be minimal (using the language features themselves instead of embedding a runtime). It's mutable but the main advantage is that generated code is native with minimal dependencies.

For example, a map generator function (lazy map) can be defined like this:

```
(defgen.xt map
  ([f seq]
   (for:iter [e (-/iter seq)]
     (yield (f e)))))
```

and expressed in different languages

in js:

```js
function* map(f,seq){
  for(let e of iter(seq)){
    yield f(e);
  };
}
```

in lua:

```lua
local function map(f,seq)
  return coroutine.wrap(function ()
    for e in iter(seq) do
      coroutine.yield(f(e))
    end
  end)
end
```

in python:

```python
def map(f,seq):
  for e in iter(seq):
    yield f(e)
```

The secret sauce here is the `for:iter` macro which has a different template for different languages. It is a `primitive` concept that works between languages. It's not really functional because I found the functional paradigm too strict for what I needed. So it ended up being a bunch of template programming.

----

Anyways, I didn't really have a point. I'm currently dogfooding the language.

One thing that I did think about was writing a runtime with immutable datastructures and having it run on python/js/lua/jvm so that it can compile itself. And If it's also possible to target one level lower... drool.

----

**Comment by helins** [comment]
Yes, targetting WASM from a higher-level language is definitely non-trivial. I don't really know JVM bytecode but since it must be suitable for the JVM itself, of course, it is already much higher level. There are WASM proposals for things like garbage collection, for instance, but it won't be actually validated for a while. Implementing it in WASM runtimes is even further down the road.

https://github.com/WebAssembly/proposals

**Comment by hoebat** [comment]
you're right. there's a rough comparison here:

https://www.quora.com/How-does-Java-bytecode-compare-to-WASM-code 

It seems like the better option would be to write something in `c` and use clang to output wasm and then read it in via js -  rather than target it directly.

**Comment by hoebat** [comment]
sorry. back to the actual issue.

Am I right in understanding
- it's currently possible with wasm.cljs to go from wasm -> wat representation
- but not wat -> wasm (because of the ambiguity you mentioned)

**Comment by helins** [comment]
No, there is no WAT involved at all :)

- `wasm` (the binary format) -> CLJ data that mimicks the bin format, but much easier to work with, and more convenient that WAT, described using Malli

- CLJ data -> `wasm`

**Comment by hoebat** [comment]
oh, you've bypassed wat entirely.  that's actually the best way.

would you have some simple hello world/add examples that I can try out?

**Comment by helins** [comment]
The very  first example in the README I suppose. There are some WASM example files at `src/wasm`, like `test.wasm` hereunder:

```
;; Reading an example file from this repo:
;;
(def decompiled
     (wasm/decompile-file "src/wasm/test.wasm"))


;; Pretty printing decompiled form (Clojure data):
;;
(clojure.pprint/pprint decompiled)
```
